[versions]
agp = "8.13.2"
kotlin = "2.0.21"
firebase = "32.2.2"

[libraries]
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase" }
firebase-database = { group = "com.google.firebase", name = "firebase-database-ktx" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }

